_extends: .github

repository:
  name: renovate-config
  description: "A collection of configuration files for Renovate"
  homepage: null
  topics: null
  private: false

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - "Get list of all JSON files"
