_extends: .github

repository:
  name: renovate-config
  description: "A collection of configuration files for Renovate"
  private: false
  is_template: true

branches:
  - name: main
    protection:
      required_status_checks:
        checks:
          - context: Get list of all JSON files
